### ISSUE TITLE
Where should the store password be collected from

### ISSUE THREAD

**Issue by mithublue** [sslcommerz/SSLCommerz-Woocommerce#3]
In the admin panel's settings page , there is field to provide "Store Password", but there is not password given in SSLCommerz dashboard

![5ea1a638-1919-46cf-b617-868c7b297401](https://user-images.githubusercontent.com/9393825/127768505-2a14bec8-11aa-45ea-b068-04f9198dafc2.png)

**Comment by TechAsif** [comment]
It will give through in your email
